# Generated by Django 4.2.6 on 2023-11-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('estadoReservaId', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('estadoReservaNombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReserva',
            fields=[
                ('tipoSolicitudId', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('tipoSolicitud', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('fechareserva', models.DateField()),
                ('horareserva', models.TimeField()),
                ('cantidadPersonas', models.IntegerField()),
                ('observaciones', models.CharField(max_length=5000)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('donante', models.BooleanField()),
                ('edad', models.IntegerField()),
                ('imagenCarnet', models.ImageField(upload_to='media/')),
                ('F_Creacion', models.DateTimeField(editable=False)),
                ('F_Modificacion', models.DateTimeField()),
                ('estadoReservaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='App.estadoreserva')),
                ('tipoSolicitudId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='App.tiporeserva')),
            ],
        ),
    ]
