# Generated by Django 4.2.6 on 2023-11-01 23:14
# Triggers para registrar la creacion y modificacion de una reserva 

""" El primer trigger se ejecutará antes de insertar una nueva fila en la tabla 'app_reserva'
el trigger se ejecutará para cada fila en la que se inserte un dato 
establece los campos 'F_Creacion' y 'F_Modificacion' de la nueva fila 
con la fecha y hora actuales del servidor de la base de datos """

""" El segundo trigger se ejecutará antes de actualizar una fila existente en la tabla 'app_reserva'
se ejecutará para cada fila que se actualice
establece el campo 'F_Modificacion' de la fila que se está actualizando 
con la fecha y hora actuales del servidor de la base de datos """

""" Los trigger se ejecutan antes de la creacion y modificacion para asegurar 
que los campos 'F_Creacion' y 'F_Modificacion' estén correctamente 
establecidos antes de que los datos se guarden en la base de datos """

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        	migrations.RunSQL(
            """
            CREATE TRIGGER before_insert_app_reserva 
            BEFORE INSERT ON app_reserva
            FOR EACH ROW
            SET NEW.F_Creacion = NOW(), NEW.F_Modificacion = NOW();
            """,
            """
            DROP TRIGGER before_insert_app_reserva;
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER before_update_app_reserva
            BEFORE UPDATE ON app_reserva
            FOR EACH ROW
            SET NEW.F_Modificacion = NOW();
            """,
            """
            DROP TRIGGER before_update_app_reserva;
            """
        ),
    ]
